### ISSUE TITLE
Empty image on Mac

### ISSUE THREAD

**Issue by tylerlong** [schnerd/chrome-headless-screenshots#1] opened 2017-04-26 08:33 UTC
I tried the code on Mac 10.12.4 and Chrome Version 58.0.3029.81 (64-bit)

There was neither exception nor error.

However the generated image is empty.

**Comment by tylerlong** [comment] 2017-04-26 09:53
It does work on Linux.

If I remove headless, it also works on Mac.

**Comment by schnerd** [comment] 2017-04-29 17:46
@tylerlong what happens if you use Chrome 59?

Note the first line in this project's README:
```
Chrome 57 brings headless browser support to Linux, and Chrome 59 will have cross-platform support (currently in beta).
```

Chrome 58 might still be linux-only for headless

**Comment by utkuturunc** [comment] 2017-04-29 22:26
I tried with 59, same result.

Also current v60 also seems to have this issue:
https://github.com/cyrus-and/chrome-remote-interface/issues/115

**Comment by tylerlong** [comment] 2017-04-30 15:29
I remember I tried canary version, same result.

**Comment by Jerskouille** [comment] 2017-05-07 10:33
Use `fromSurface: true` : https://bugs.chromium.org/p/chromium/issues/detail?id=687407 - https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot .

**Comment by blakedietz** [comment] 2017-05-09 01:38
@Jerskouille 's solution works on macOS. Thanks for that tip. You can use the script from here: https://medium.com/@dschnr/using-headless-chrome-as-an-automated-screenshot-tool-4b07dffba79a and just modify the line as follows:

```js
     // before
     const screenshot = await Page.captureScreenshot({format});
     //after 
     const screenshot = await Page.captureScreenshot({format, fromSurface: true});
```

**Comment by blakedietz** [comment] 2017-05-09 02:00
@Jerskouille that works! If you use the script found in https://medium.com/@dschnr/using-headless-chrome-as-an-automated-screenshot-tool-4b07dffba79a and modify the line.

```js
      const screenshot = await Page.captureScreenshot({format);
```
to
```js
        const screenshot = await Page.captureScreenshot({format, fromSurface: true});
```

**Comment by LukasBombach** [comment] 2017-05-09 13:24
Confirming that `fromSurface: true` works with canary on os x. Thank you!

**Comment by JustinYi922** [comment] 2017-05-10 03:58
我尝试了一下，缺失去掉--headless，Screenshot saved。但是这个png图片不是整个网页。很抱歉，原谅我英文不是很好。我还在努力翻译中...

**Comment by ArkinDharawat** [comment] 2017-05-12 14:56
I am using Canary 60 and os x Sierra. I changed my code to `fromSurface: true` But I still get a blank .png file

**Comment by xgz123** [comment] 2017-05-15 09:27
@ArkinDharawat I am using Canary 60 but on El Capitan, works fine

**Comment by pouu69** [comment] 2017-06-07 07:22
Confirming that `fromSurface: true` works with  on mac(sierra). Thank you!

**Comment by neilthawani** [comment] 2017-06-19 19:50
Unable to get this to work with `fromSurface: true`...

**Comment by neilthawani** [comment] 2017-06-19 19:59
Nor by upgrading Node 8.1.2.

**Comment by PaulAik** [comment] 2017-06-25 21:46
Working for me without the `fromSurface: true` option on canary Version 61.0.3141.0 (producing a blank 1x1 screenshot in standard chrome on the same machine).

Give the latest canary build a shot as an alternative!

**Comment by gorjanz** [comment] 2017-07-13 08:46
Using:
```OS X 10.11.6``` and ```Chrome canary version 61.0.3156.0 (Official Build) canary (64-bit)```

Everything works, but the image is always empty and gray at the end.

Also, can you please clarify what cases require the Emulation.forceViewport call, since in my version of the chrome-remote-interface package ```0.24.1```, this function does not exist on that object.
Is there another simple way of achieving the same?

Anyway, I keep digging through the docs, here: https://chromedevtools.github.io/devtools-protocol
to see why the gray image all the time. If you have some pointers, I would be very gratefull :)

PS: adding ```fromSurface: true``` does not help...

**Comment by dotneet** [comment] 2017-07-13 09:15
@gorjanz 
Chrome canary may have the bug. I opened the issue at chromium today.
https://bugs.chromium.org/p/chromium/issues/detail?id=741969

**Comment by antitoxic** [comment] 2017-07-13 11:55
This is also happening with webdriver (selenium) + chromedriver.

**Comment by dotneet** [comment] 2017-07-16 12:13
The bug of Chrome Canary is fixed and I could confirmed with latest canary.
But this tool might doesn't work with Chrome Canary.
Because this tool uses the command -- Emulation.forceViewPort() -- obsoleted  in chrome61.

**Comment by MONOmah-V** [comment] 2017-07-17 10:30
Confirm on `Chrome Version 59.0.3071.115 (Official Build) (64-bit)`, `Windows 10`. Completely black .png with `--headless` and `--disable-gpu`. Without those switches screenshot is saved correctly.

**Comment by bschwartz757** [comment] 2017-07-19 00:00
Hello! I'm trying to get a screenshot - I cobbled together a script from a few different examples, mostly from [here](https://developers.google.com/web/updates/2017/04/headless-chrome#cli) and [here](https://github.com/cyrus-and/chrome-remote-interface/wiki/Wait-for-a-specific-element). I'm getting a white page as output each time. I'm using `chromeLauncher` to launch the page:
```
const fs = require('fs');
const chromeLauncher = require('chrome-launcher');
const CDP = require('chrome-remote-interface');

function launchChrome(headless = true) {
  return chromeLauncher.launch({
    // port: 9222, // Uncomment to force a specific port of your choice.
    chromeFlags: [
      '--screenshot',
      '--window-size=1440,900',
      '--disable-gpu',
      headless ? '--headless' : ''
    ]
  });
}
```
I wasn't running with the '--screenshot' flag, but when I added it I got this:
<img width="898" alt="screen shot 2017-07-18 at 4 22 53 pm" src="https://user-images.githubusercontent.com/7519644/28344144-9656a6e6-6bd6-11e7-82be-b9be39ea60de.png">

I also tried commenting out
       '--disable-gpu',
      headless ? '--headless' : ''

Running this script I get
```
launchChrome()
  .then(async chrome => {
    const version = await CDP.Version({
      port: chrome.port
    });
    console.log(version['User-Agent']);
  });
```
--> `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/61.0.3159.0 Safari/537.36`

Seems like this is possibly OSX 10.12 related?

Interestingly, using WebDriverIO/ChromeDriver, I am able to take screenshots, so I wonder if this could also be chromeLauncher related (which would be a real shame as it seems like an awesome tool!)

My intention was to use this awesome [wait for element technique](https://github.com/cyrus-and/chrome-remote-interface/wiki/Wait-for-a-specific-element) from the CDP wiki examples. The script does indeed capture the element I need, but I want to take a screenshot of the page when that happens. Here's my script for reference:
```
const fs = require('fs');
const chromeLauncher = require('chrome-launcher');
const CDP = require('chrome-remote-interface');

function launchChrome(headless = true) {
  return chromeLauncher.launch({
    // port: 9222, // Uncomment to force a specific port of your choice.
    chromeFlags: [
      '--window-size=412,732',
      '--disable-gpu',
      headless ? '--headless' : ''
    ]
  });
}

async function nodeAppears(client, selector) {
  // browser code to register and parse mutations
  const browserCode = (selector) => {
    return new Promise((fulfill, reject) => {
      new MutationObserver((mutations, observer) => {
          // add all the new nodes
          const nodes = [];
          mutations.forEach((mutation) => {
            nodes.push(...mutation.addedNodes);
          });
          // fulfills if at least one node matches the selector
          if (nodes.find((node) => node.matches(selector))) {
            observer.disconnect();
            fulfill();
          }
        })
        .observe(document.body, {
          childList: true
        });
    });
  };
  // inject the browser code
  const {
    Runtime
  } = client;
  await Runtime.evaluate({
    expression: `(${browserCode})(${JSON.stringify(selector)})`,
    awaitPromise: true
  });
}

(async function() {

  const chrome = await launchChrome();

  CDP({
      port: chrome.port
    }, async(client) => {

      const {
        Page,
        Runtime,
        DOM,
        Emulation
      } = client;

      await Promise.all([Page.enable(), Runtime.enable(), DOM.enable()]);

      Page.navigate({
        url: 'http://www.eff.org'
      });

      // Wait for window.onload before doing stuff.
      Page.loadEventFired(async() => {

        // Set up viewport resolution, etc.
        const deviceMetrics = {
          width: 1440,
          height: 900,
          deviceScaleFactor: 0,
          mobile: false,
          fitWindow: false,
        };
        await Emulation.setDeviceMetricsOverride(deviceMetrics);

        try {

          // wait for the element to be present *example selector*
          await nodeAppears(client, 'body');
          console.log('OK');

          const screenshot = await Page.captureScreenshot({
            format: 'png',
            fromSurface: true
          });
          const buffer = new Buffer(screenshot.data, 'base64');
          await fs.writeFile('screenshot.png', buffer, 'base64', function(err) {
            if (err) {
              console.error(err);
            }
            console.log('file created')
            client.close();
            chrome.kill(); // Kill Chrome.
          })

        } catch (err) {
          console.error(err);
        } //finally {
        //   client.close();
        //   chrome.kill(); // Kill Chrome.
        // }
      })
    })
    .on('error', (err) => {
      console.error(err);
    });
})();

```

**Comment by schnerd** [comment] 2017-07-26 06:31
Got around to doing some more testing here–it seems like fromSurface helps out in version 60, but not in 61+ (tested on Chrome 62, currently in canary)

It's clear that headless chrome is not stable on Mac yet, similar issues have been reported in the chrome-remote-interface repo (see cyrus-and/chrome-remote-interface#115). Accordingly, I'm going to close this issue and recommend that users report their issues in Chromium or [ChromeDevTools/devtools-protocol](https://github.com/ChromeDevTools/devtools-protocol). In the meantime, you can use docker or vagrant on your mac (Dockerfile or Vagrantfile pull requests welcome).

I've updated the README in this repo to clarify what environments and chrome versions we're currently targeting.

**Closed by schnerd** 2017-07-26 06:31 UTC
